import type { TCaseHearing } from "@/types/hearing.type";

export const hearings: TCaseHearing[] = [
  {
    id: "1",
    case_number: "CIV-2025-00123",
    hearing_date: "2025-02-01",
    hearing_time: "10:30",
    party_name: "Rahim Uddin",
    party_type: "Plaintiff",
    lawyer_name: "Adv. Kamal Hossain",
    court_name: "Dhaka District Court",
    case_type: "Civil",
    status: "Scheduled",
    notes: "Initial hearing",
    created_at: "2025-01-25",
  },
  {
    id: "2",
    case_number: "CR-2025-00456",
    hearing_date: "2025-02-02",
    hearing_time: "13:15",
    party_name: "Abdul Karim",
    party_type: "Defendant",
    lawyer_name: "Adv. Shirin Akter",
    court_name: "Chattogram Session Court",
    case_type: "Criminal",
    status: "Completed",
    notes: "Verdict delivered",
    created_at: "2025-01-26",
  },
  {
    id: "3",
    case_number: "FAM-2025-00278",
    hearing_date: "2025-02-03",
    hearing_time: "11:00",
    party_name: "Maira Islam",
    party_type: "Petitioner",
    lawyer_name: "Adv. Tanvir Rahman",
    court_name: "Gazipur Family Court",
    case_type: "Family",
    status: "Postponed",
    notes: "Rescheduled due to absence",
    created_at: "2025-01-27",
  },
  {
    id: "4",
    case_number: "LAB-2025-00912",
    hearing_date: "2025-02-04",
    hearing_time: "09:45",
    party_name: "Jahangir Alam",
    party_type: "Complainant",
    lawyer_name: "Adv. Nusrat Jahan",
    court_name: "Labour Court, Narayanganj",
    case_type: "Labour",
    status: "Scheduled",
    notes: "Wage dispute hearing",
    created_at: "2025-01-28",
  },
  {
    id: "5",
    case_number: "CIV-2025-00321",
    hearing_date: "2025-02-05",
    hearing_time: "12:00",
    party_name: "GreenTech Ltd.",
    party_type: "Defendant",
    lawyer_name: "Adv. Arif Chowdhury",
    court_name: "Sylhet District Court",
    case_type: "Commercial",
    status: "Cancelled",
    notes: "Case withdrawn",
    created_at: "2025-01-29",
  },
];
